

services:
  # 1. The Database (We already had this, now dockerized)
  postgres:
    image: postgres:18
    container_name: zomato_db
    environment:
      POSTGRES_DB: zomato_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - zomato-net

  # 2. The Cache (New for Phase 2)
  redis:
    image: redis:7-alpine
    container_name: zomato_redis
    ports:
      - "6379:6379"
    networks:
      - zomato-net

volumes:
  postgres_data:

networks:
  zomato-net:
    driver: bridge