package com.zomato.clone.order.entity;

import com.zomato.clone.restaurant.entity.MenuItem;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;

/**
 * OrderItem represents a single food item inside an Order.
 * It acts as a junction entity between Order and MenuItem
 * and stores order-specific details like quantity and price at order time.
 */

@Entity
@Data
@Table(name = "order_times")  // Table to store items belonging to an order
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class OrderItem {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id; // primary key for OrderItem, Auto-generated by the database

    /**
     * Reference to the Order this item belongs to.
     * Many OrderItems can belong to one Order.
     * LAZY fetch to avoid loading Order unless required.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "order_id", nullable = false)
    private Order order; //

    /**
     * Reference to MenuItem that was ordered
     * many orderItems can belong to same menuItem
     * similarly LAZY fetch improves performance.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "menu_item_id", nullable = false)
    private MenuItem menuItem;


    @Column(nullable = false)
    private Integer quantity; // quantity of this menu item is ordered

    /**
     * Snapshot price of the MenuItem at the time of ordering.
     * This is stored to preserve historical pricing
     * even if the menu price changes later.
     */
    @Column(nullable = false, precision = 10, scale = 2)
    private BigDecimal price;
}
